"""add_user_security_and_profile_fields

Revision ID: 7223b294fbbb
Revises: 0e0402c01692
Create Date: 2026-05-18 15:00:12.600285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7223b294fbbb'
down_revision: Union[str, Sequence[str], None] = '0e0402c01692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('refresh_token_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('avatar_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('biometric_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('app_pin', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'app_pin')
    op.drop_column('users', 'biometric_enabled')
    op.drop_column('users', 'avatar_id')
    op.drop_column('users', 'refresh_token_expiry')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
