"""add cascade delete to models

Revision ID: 960f3b57a906
Revises: 7223b294fbbb
Create Date: 2026-05-19 02:12:01.012111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960f3b57a906'
down_revision: Union[str, Sequence[str], None] = '7223b294fbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('citations_chunk_id_fkey'), 'citations', type_='foreignkey')
    op.drop_constraint(op.f('citations_qa_id_fkey'), 'citations', type_='foreignkey')
    op.create_foreign_key(None, 'citations', 'document_chunks', ['chunk_id'], ['docuchunk_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'citations', 'qa_history', ['qa_id'], ['qahistory_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('document_chunks_document_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['document_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('documents_notebook_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'notebooks', ['notebook_id'], ['notebook_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notebooks_user_id_fkey'), 'notebooks', type_='foreignkey')
    op.create_foreign_key(None, 'notebooks', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('qa_history_notebook_id_fkey'), 'qa_history', type_='foreignkey')
    op.create_foreign_key(None, 'qa_history', 'notebooks', ['notebook_id'], ['notebook_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('summaries_document_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'documents', ['document_id'], ['document_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_document_id_fkey'), 'summaries', 'documents', ['document_id'], ['document_id'])
    op.drop_constraint(None, 'qa_history', type_='foreignkey')
    op.create_foreign_key(op.f('qa_history_notebook_id_fkey'), 'qa_history', 'notebooks', ['notebook_id'], ['notebook_id'])
    op.drop_constraint(None, 'notebooks', type_='foreignkey')
    op.create_foreign_key(op.f('notebooks_user_id_fkey'), 'notebooks', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_notebook_id_fkey'), 'documents', 'notebooks', ['notebook_id'], ['notebook_id'])
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_document_id_fkey'), 'document_chunks', 'documents', ['document_id'], ['document_id'])
    op.drop_constraint(None, 'citations', type_='foreignkey')
    op.drop_constraint(None, 'citations', type_='foreignkey')
    op.create_foreign_key(op.f('citations_qa_id_fkey'), 'citations', 'qa_history', ['qa_id'], ['qahistory_id'])
    op.create_foreign_key(op.f('citations_chunk_id_fkey'), 'citations', 'document_chunks', ['chunk_id'], ['docuchunk_id'])
    # ### end Alembic commands ###
